#!/usr/bin/env bash

case $1 in
  collector)
    ./scripts/run_collector.sh
    ;;
  db)
    ./scripts/start_local_db.sh
    ;;
  reset_db)
    ./scripts/reset_db.sh
    ;;
  gen_keys)
    ./scripts/gen_keys.sh
    ;;
  discord)
    ./scripts/run_discord_bot.sh
    ;;
  *)
    echo -e "Please provide a valid project to execute.\nValid Projects: ("
    echo -e "  collector"
    echo -e "  discord"
    echo -e "  db"
    echo -e "  reset_db"
    echo -e "  gen_keys"
    echo -e ")"
    exit 1
    ;;
esac
